configurationset:
  - configuration:
      name:
        spotify_auth
        #Authorization: Basic This is a different (and better) way of providing username:password of https://username:password@accounts.spotify.com/api/token
      client_id: SPOTIFY_CLIENT_ID
      client_secret: SPOTIFY_CLIENT_SECRET
  - configuration:
      name:
        news_config
        #Authorization: Basic This is a different (and better) way of providing username:password of https://username:password@accounts.spotify.com/api/token
      apiKey: NEWSAPI_APIKEY
ruleset:
  - query: "[ALL]"
    rules:
      - predicate: true
        action: allow
